### PR TITLE
Bump version to 3.34.3

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
👍  if it builds and I forget to merge, please ping me.

**Comment by maartenbreddels** [comment]
Could you try a rerender:
```$ conda smithy rerender``` (in the progressbar2-feedstock dir)

**Comment by nehaljwani** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
Yay! All checks passed :smiley_cat:

**Comment by nehaljwani** [comment]
Ping @maartenbreddels !

**Comment by maartenbreddels** [comment]
Excellent, thanks

**Pull request merged**
